services:
  db:
    image: postgres:16
    container_name: english_noting_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sonha
      POSTGRES_PASSWORD: sonha
      POSTGRES_DB: english_noting
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    container_name: english_noting_api
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: sonha
      POSTGRES_PASSWORD: sonha
      POSTGRES_DB: english_noting
      DATABASE_URL: postgres://sonha:sonha@db:5432/english_noting?sslmode=disable
      OPENAI_API_KEY: your_openai_api_key_here
      LOG_LEVEL: debug
      APP_PORT: 8080
      APP_HOST: 0.0.0.0
    ports:
      - "8080:8080"

volumes:
  pgdata: