services:
  db:
    image: postgres:16
    container_name: english_noting_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sonha
      POSTGRES_PASSWORD: sonha
      POSTGRES_DB: english_noting
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 